In [1]:
def f(x):
  f.counter = getattr(f, "counter", 0) + 1
  return "Monty Python"
for i in range(10):
  f(i)
print(f.counter)

10


# Learning about Classes

In [2]:
class Robot:
    """Represents a robot, with a name."""

    # A class variable, counting the number of robots
    population = 0

    def __init__(self, name):
        """Initializes the data."""
        self.name = name
        print("(Initializing {})".format(self.name))

        # When this person is created, the robot
        # adds to the population
        Robot.population += 1

    def die(self):
        """I am dying."""
        print("{} is being destroyed!".format(self.name))

        Robot.population -= 1

        if Robot.population == 0:
            print("{} was the last one.".format(self.name))
        else:
            print("There are still {:d} robots working.".format(
                Robot.population))

    def say_hi(self):
        """Greeting by the robot.

        Yeah, they can do that."""
        print("Greetings, my masters call me {}.".format(self.name))

    @classmethod
    def how_many(cls):
        """Prints the current population."""
        print("We have {:d} robots.".format(cls.population))


droid1 = Robot("R2-D2")
droid1.say_hi()
Robot.how_many()

droid2 = Robot("C-3PO")
droid2.say_hi()
Robot.how_many()

print("\nRobots can do some work here.\n")

print("Robots have finished their work. So let's destroy them.")
droid1.die()
droid2.die()

Robot.how_many()

(Initializing R2-D2)
Greetings, my masters call me R2-D2.
We have 1 robots.
(Initializing C-3PO)
Greetings, my masters call me C-3PO.
We have 2 robots.

Robots can do some work here.

Robots have finished their work. So let's destroy them.
R2-D2 is being destroyed!
There are still 1 robots working.
C-3PO is being destroyed!
C-3PO was the last one.
We have 0 robots.


# Task 7

Task 7 Tic Tac Toe
This is a TEAM ACTIVITY. MUST BE DONE IN TEAMS OF 2 or 3 people.

The goal of this task is to DESIGN AND IMPLEMENT a simple Tic Tac Toe game in Python that can be played by two human players. (This task does not involve designing the game AI.)

Your game *must* use multiple functions, each with just one job each. Tic-Tac-Toe is just complicated enough that 
I want you to sketch out the DESIGN of the program you will write before you actually start to code! A little bit of thinking about design goes a long way in making the implementation better.

DESIGN PHASE
First, work out on a high level what game logic you need and what tasks your game needs to be able to do, e.g. draw the board, let player mark X or O, test whether the move is valid or invalid, update the board, etc.
Next, break the tasks into individual functions
Next, figure out the parameters that each function will take and what each function will return, i.e., I want you to design the API of your game.

IMPLEMENTATION
Your team MUST explain your design to me before you do implementation. After you do this, make your program work!
Note: It's totally ok if you need to change some aspect of the design and/or API when you actually start coding. That's the way coding works!
 
 BONUS: Update your user interface to let one human play against the computer. Implement a function that controls the computer's play with a simple rule: The computer moves by picking an unoccupied space on the board at random.

In [33]:
# figuring out how to get diagonals
import numpy as np

positions = np.array([0,1,2,3,4,5,6,7,8])
board = positions.reshape((3,3))

diagonal1 = np.diagonal(board)
diagonal2 = np.diag(np.fliplr(board))
horizontal = board[2]
vertical = board [0][0]

print(board)
print(diagonal1)
print(diagonal1[0])
print(diagonal2)
print(horizontal)
print(vertical)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]
0
[2 4 6]
[6 7 8]
0


In [88]:
import numpy as np

#already defined somewhere...
positions = np.array([0,1,2,'x','x','x',6,7,8])
board = positions.reshape((3,3))


#checking that all members of a list are the same
def checkEqual1(iterator):
    iterator = iter(iterator)
    try:
        first = next(iterator)
    except StopIteration:
        return True
    return all(first == rest for rest in iterator)

#printing results
print(board)
diagonal1 = np.diagonal(board)
diagonal2 = np.diag(np.fliplr(board))
print(checkEqual1(diagonal1))
print(checkEqual1(diagonal2))

#check for horizontals
for i in range(3):
    horizontal = board[i]
    print(checkEqual1(horizontal))

#check verticals
vertical1 = [board[i][0] for i in range(3)]      
vertical2 = [board[i][1] for i in range(3)]  
vertical3 = [board[i][2] for i in range(3)]

print(checkEqual1(vertical1))
print(checkEqual1(vertical2))
print(checkEqual1(vertical3))

def check_winner()

    


[['0' '1' '2']
 ['x' 'x' 'x']
 ['6' '7' '8']]
False
False
False
True
False
False
False
False


In [95]:
import numpy as np
#already defined somewhere...
positions = np.array([0,1,2,'x','x','x',6,7,8])
board = positions.reshape((3,3))

#checking that all members of a list are the same
def check_equal(iterator):
    iterator = iter(iterator)
    try:
        first = next(iterator)
    except StopIteration:
        return True
    return all(first == rest for rest in iterator)

def check_winner():
    checks = []
    
    diagonal1 = np.diagonal(board)
    diagonal2 = np.diag(np.fliplr(board))
    checks.append(check_equal(diagonal1))
    checks.append(check_equal(diagonal2))

    #check for horizontals
    for i in range(3):
        horizontal = board[i]
        checks.append(check_equal(horizontal))

    #check verticals

    vertical1 = [board[i][0] for i in range(3)]      
    vertical2 = [board[i][1] for i in range(3)]  
    vertical3 = [board[i][2] for i in range(3)]
    checks.append(check_equal(vertical1))
    checks.append(check_equal(vertical2))
    checks.append(check_equal(vertical3))
    
    if True in checks:
        return True
    else:
        return False

# Task 7
Final

In [98]:
import numpy as np

def main():
    count = 0
    while True:
        print_board()

        while True:
            choice = input('Player one, pick a tile.')
            if choice == 'quit':
                return
            if check_valid(choice) == True:
                break
            print('Not a valid choice')
        
        place_mark('X',choice)
        
        if check_winner() == True:
            print(board)
            print('Winner is player one' )
            return
        count+=1
        if count == 9:
            break

        print_board()
        
        while True:
            choice = input('Player two, pick a tile.')
            if check_valid(choice) == True:
                break
            if choice == 'quit':
                return
            print('Not a valid choice')
        place_mark('O',choice)
        if check_winner() == True:
            print(board)
            print('Winner is player two')
            return
        count+=1
    print('Tie game')

def init_board():
    return np.matrix([['1','2','3'],['4','5','6'],['7','8','9']])

def print_board():
    print(board)
    return

def check_valid(choice):
    choice = int(choice)
    if choice == 1 and board[0,0] == '1':
        return True
    elif choice == 2 and board[0,1] == '2':
        return True
    elif choice == 3 and board[0,2] == '3':
        return True
    elif choice == 4 and board[1,0] == '4':
        return True
    elif choice == 5 and board[1,1] == '5':
        return True
    elif choice == 6 and board[1,2] == '6':
        return True
    elif choice == 7 and board[2,0] == '7':
        return True
    elif choice == 8 and board[2,1] == '8':
        return True
    elif choice == 9 and board[2,2] == '9':
        return True
    else:
        return False

def place_mark(mark,choice):
    choice = int(choice)
    if choice == 1 and board[0,0] == '1':
        board[0,0] = str(mark)
    elif choice == 2 and board[0,1] == '2':
        board[0,1] = str(mark)
    elif choice == 3 and board[0,2] == '3':
        board[0,2] = str(mark)
    elif choice == 4 and board[1,0] == '4':
        board[1,0] = str(mark)
    elif choice == 5 and board[1,1] == '5':
        board[1,1] = str(mark)
    elif choice == 6 and board[1,2] == '6':
        board[1,2] = str(mark)
    elif choice == 7 and board[2,0] == '7':
        board[2,0] = str(mark)
    elif choice == 8 and board[2,1] == '8':
        board[2,1] = str(mark)
    elif choice == 9 and board[2,2] == '9':
        board[2,2] = str(mark)

def check_winner():
    checks = []

#check for diagonals
    diagonal1 = np.diagonal(board)
    diagonal2 = np.diag(np.fliplr(board))

    if diagonal1[0] == diagonal1[1] and diagonal1[0] == diagonal1[1]:
        return True

    for i in range(3):
        if board[0,i] == board[1,i] and board[0,i] == board[2,i]:
            return True
        if board[i,0] == board[i,1] and board[i,1] == board[i,2]:
            return True
    return False

board = init_board()
main()

[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]
Player one, pick a tile.1
[['X' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]
Player two, pick a tile.2
[['X' 'O' '3']
 ['4' '5' '6']
 ['7' '8' '9']]
Player one, pick a tile.4
[['X' 'O' '3']
 ['X' '5' '6']
 ['7' '8' '9']]
Player two, pick a tile.7
[['X' 'O' '3']
 ['X' '5' '6']
 ['O' '8' '9']]
Player one, pick a tile.5
[['X' 'O' '3']
 ['X' 'X' '6']
 ['O' '8' '9']]
Winner is player one


# Task 7
v2

In [ ]:
import numpy as np
import random

def main():
    count = 0 #begins the count of the game
    while True:
        print_board()
        
        #player 1 plays
        while True:
            choice = input('Player one, pick a tile.')
            if choice == 'quit':
                return
            if choice == 'save':
                savedBoard = board
                continue
            if choice == 'load':
                board == savedBoard
                print(board)
                continue
            if check_valid(choice) == True:
                break
            print('Not a valid choice')
        # change the position to an "X" in the board
        place_mark('X',choice)
        if check_winner() == True:
            print(board)
            print('Winner is player one' )
            return
        count+=1
        if count == 9:
            break

        print_board()
        
        # the computer playing, choosing randomly from the available choices
        while True:
            choice = random.choice(range(1,10))
            if check_valid(choice) == True:
                break
            if choice == 'quit':
                return
        place_mark('O',choice)
        if check_winner() == True:
            print(board)
            print('Winner is player two')
            return
        count+=1
    print('Tie game')

def init_board():
    return np.matrix([['1','2','3'],['4','5','6'],['7','8','9']])

def print_board():
    print(board)
    return

def check_valid(choice):
    choice = int(choice)
    if choice == 1 and board[0,0] == '1':
        return True
    elif choice == 2 and board[0,1] == '2':
        return True
    elif choice == 3 and board[0,2] == '3':
        return True
    elif choice == 4 and board[1,0] == '4':
        return True
    elif choice == 5 and board[1,1] == '5':
        return True
    elif choice == 6 and board[1,2] == '6':
        return True
    elif choice == 7 and board[2,0] == '7':
        return True
    elif choice == 8 and board[2,1] == '8':
        return True
    elif choice == 9 and board[2,2] == '9':
        return True
    else:
        return False


def place_mark(mark,choice):
    choice = int(choice)
    if choice == 1 and board[0,0] == '1':
        board[0,0] = str(mark)
    elif choice == 2 and board[0,1] == '2':
        board[0,1] = str(mark)
    elif choice == 3 and board[0,2] == '3':
        board[0,2] = str(mark)
    elif choice == 4 and board[1,0] == '4':
        board[1,0] = str(mark)
    elif choice == 5 and board[1,1] == '5':
        board[1,1] = str(mark)
    elif choice == 6 and board[1,2] == '6':
        board[1,2] = str(mark)
    elif choice == 7 and board[2,0] == '7':
        board[2,0] = str(mark)
    elif choice == 8 and board[2,1] == '8':
        board[2,1] = str(mark)
    elif choice == 9 and board[2,2] == '9':
        board[2,2] = str(mark)

def check_winner():

    diagonal1 = np.diagonal(board)
    diagonal2 = np.diag(np.fliplr(board))

    if diagonal1[0] == diagonal1[1] and diagonal1[0] == diagonal1[2]:
        return True
    if diagonal2[0] == diagonal2[1] and diagonal2[0] == diagonal2[2]:
        return True

    for i in range(3):
        if board[0,i] == board[1,i] and board[0,i] == board[2,i]:
            return True
        if board[i,0] == board[i,1] and board[i,0] == board[i,2]:
            return True
    return False

board = init_board()
savedBoard = board
main()

# Task 8
Task 8 - Mean, Median, and Mode (Computed From Scratch)
1) Write a function that, given an arbitrary list of numbers (or a range, or a tuple of numbers) computes the mean.
2) Write a function that, given an arbitrary list of numbers (or a range of numbers, or a tuple of numbers) computes the median.
3) Write a function that, given an arbitrary list of numbers (or a range, or a tuple of numbers) computes the mode.
see docstring below for examples
"""

list1 = [2,3,4]
>>> mean(list1) = 3
>>> median(list1) = 3
>>> mode(list1) = None

list2 = [10,1,4,3,2,10]
>>> mean(list2) = 5
>>> median(list2) = 3.5
>>> mode(list2) = 10

range1 = range(2,5)
>>> mean(range1) = 3
>>> median(range1) = 3
>>> mode(range1) = None

range2 = range(1,101)
>>> mean(range2) = 5050
>>> median(range2) = 50.5
>>> mode(range2) = None

tuple1 = (10,4,6,8,2)
>>> mean(tuple1) = 6
>>> median(range1) = 6
>>> mode(range1) = None

tuple2 = (10,4,6,8,2,10000,4)
>>> mean(tuple1) = 1433.4 
>>> median(range1) = 6
>>> mode(range1) = 4

In [134]:
import collections

def mean(thing):
    sum = 0
    for i in thing:
        sum = sum + i
    return sum / len(thing)

def median(thing):
    thing_list = sorted(list(thing))
    length_list = len(thing_list)
    if length_list % 2 == 0:
        return (thing_list[length_list / 2 - 1] + thing_list[length_list / 2]) / 2
    else:
        return thing_list[int(length_list / 2)] 

def mode(thing):
    freq_list = collections.Counter(thing).most_common(1) 
    if freq_list[0][1] == 1:
        return 'None'
    else:
        return freq_list[0][0]    
    
list1 = [2,3,4]
print(mean(list1))
print(median(list1))
print(mode(list1))

3.0
3
None
